# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "f5ec8833-fcf4-4e0c-ba4c-b1514bec6d88"

default_platform :android

def changelog_from_commits
    # http://git-scm.com/docs/pretty-formats
    return changelog_from_git_commits(
        commits_count: 10,
        pretty: '• The author of %h was %an, %ar%nThe title was >>%s<<%n',
        merge_commit_filtering: 'exclude_merges'
     )
end

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do

  # build the release variant
  gradle(task: "assembleRelease")

  change_log = changelog_from_commits

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "58e62ee3069f7917e79219f38e49282a7175db1c",
    build_secret: "c6cc2dfc4e210992561d1150cd369fd891aa936cdc0f1c83e746c46d041c299b",
    notes: change_log,
    notifications: true
  )
end
